### ISSUE TITLE
New Dub TAMIL introduced

### ISSUE THREAD

**Issue by jimmyedagawa78** [roshinc/release-calendar-filter-for-crunchyroll#16]
![image](https://github.com/roshinc/release-calendar-filter-for-crunchyroll/assets/30567984/7b7705d7-e174-45ea-95eb-5d400a9db011)

Visible on https://www.crunchyroll.com/simulcastcalendar?date=2023-07-28

**Comment by roshinc** [comment]
Thanks for the issue, working on this now, weirdly I think Tamil dubs are region locked

![image](https://github.com/roshinc/release-calendar-filter-for-crunchyroll/assets/2994406/65bbdc1a-5ef6-44d6-a3df-90326dc1d297)

But it should be ok, I can add it to the dub list and it should be treated like other dubs when present.

**Comment by roshinc** [comment]
@jimmyedagawa78 This should be fixed, version 1.1.3 should now be live, if its not updated for you, you can go to the your browsers extension manager page and should be able to see a update button, I cannot test this particular fix because Tamil as a dub option are not visible to me.

Feel free to close this issue if the fix is working,

Thank You

**Comment by jimmyedagawa78** [comment]
Thanks a lot! Your extension is a lifesaver. It's weird how it's region locked to India, it might be a licensing issue. I can confirm it works now!! I'll close this issue now, thanks again!!
![image](https://github.com/roshinc/release-calendar-filter-for-crunchyroll/assets/30567984/e6e1a04e-9b72-443a-8d13-f638302f2c80)
